version: '3.8'
services:
  bytebase:
    image: bytebase/bytebase:3.3.0
    container_name: bytebase
    init: true
    restart: always
    ports:
      - "8093:8080"
    environment:
      - PG_URL=postgresql://eclipse:dlzmfflqtm@192.168.121.91:5432/bytebase
    volumes:
      - ./data:/var/opt/bytebase

