version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8_sgp_qa1
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: dlzmfflqtm
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/config:/etc/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
        #      - ./mysql/etc:/etc/
      - /etc/localtime:/etc/localtime
        #    user: "${USER_ID}:${GROUP_ID}"    
