services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'        # HTTP
      - '443:443'      # HTTPS
      - '81:81'        # Admin UI
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
      DISABLE_IPV6: 'true'
    #cap_add:
    #  - NET_ADMIN
